version: '3.9'

services:
  mysql: 
    image: mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
      MYSQL_DATABASE: sales
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "mysql_db:/var/lib/mysql"

volumes:
  mysql_db: